### PR TITLE
The test harness is set up and ready to go

### PR DESCRIPTION
**Pull request by cjsauer**
@elGatoMantocko can you try this out so I can see if things are working. There might be some hidden dependencies that aren't installed on meteor-shire.

### CODE REVIEW

**Comment by cjsauer** [comment]
I think I'd like to add the course creation form redirect before I merge this. That would round out the tests for what we've got so far.

**Comment by cjsauer** [comment]
Before I forget, I'd also like to add in the Jasmine integration testing framework too. Leaving this here as a note to myself

**Comment by elGatoMantocko** [comment]
I gave this a go over the weekend and it looked good. However, it did not work on Windows. I think it is a part of the symlink problem though. I will make a few changes to the fix script and get back to you.

**Comment by cjsauer** [comment]
What's the exact error you're getting?

**Comment by elGatoMantocko** [comment]
There is no error. The tests just aren't running in my environment at home. They run fine on OSX and Ubuntu on VirtualBox for Mac OS.

I will take a screenshot and put it here when I get home today. Again, I think this is just part of Windows symlink problems in VirtualBox.

I am going to try [this fix](http://www.ahtik.com/blog/fixing-your-virtualbox-shared-folder-symlink-error/) when i get back.

**Comment by cjsauer** [comment]
Ah ok well as long as they can run somewhere it should be fine. Plus we have Travis running, so any pushes and pull requests will auto run them for us.

**Pull request merged**
