### PR TITLE
Top nav

### PR DESCRIPTION
**Pull request by elGatoMantocko**
I think the top nav is ready to be pulled into develop. There are going to be some more tweaks, but I think the styling is getting close to our end goal for this sprint.

Take a look at what I worked on today and let me know.

### CODE REVIEW

**Comment by cjsauer** [comment]
Could you pull the navigation bar into its own template? I think that'd clean up main quite a bit.

**Comment by elGatoMantocko** [comment]
Yeah sure. I will get on it.

**Comment by elGatoMantocko** [comment]
Just for reference. I intentionally put nav.html into the directory in this fasion. I think we should follow the idea that any unique non-page specific templates/content should be in the client directory. Any pages that a user can navigate to would be in a views directory.

How does that sound?

**Comment by cjsauer** [comment]
Good idea. I'd say this looks good.

**Pull request merged**
